[package]
name = "LiteXLPluginLab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rohanasan = "0.5.46"
serde_json = "1.0.116"
